# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Script-Resume
version:      1.0
version_from: lib/Script/Resume.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    File::Basename:                0
    FileHandle:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
